/*
CRIAR AS ESTRUTURAS DAS TABELAS NO SQL DEVELOPER

1. Criar as chaves primárias e estrangeiras
2. Os campos PRODUTO, CATEGORIA e MATERIA_PRIMA devem ser únicos
3. O campo QUANTIDADE não pode aceitar valor nulo
4. A CATEGORIA deve ser criada para receber valores restritos a DOCE, BEBIDA e CONGELADOO
5. Trazer as regras de restrições da tabela CATEGORIA.

*/




CREATE TABLE categoria (
    cod_categoria NUMBER CONSTRAINT PK_CATEGORIA_CODCAT PRIMARY KEY,
    categoria VARCHAR2(255) CONSTRAINT UK_CATEGORIA_CAT UNIQUE CONSTRAINT CK_CATEGORIA_CAT CHECK (CATEGORIA IN('DOCE', 'BEBIDA', 'CONGELADO'))
);

CREATE TABLE materia_prima (
    cod_materia_prima NUMBER CONSTRAINT PK_MATPRI_CODMATPRI PRIMARY KEY,
    materia_prima VARCHAR2(255) CONSTRAINT UK_MATPRI_MATPRI UNIQUE
);

CREATE TABLE produto (
    cod_produto NUMBER CONSTRAINT PK_PRODUTO_CODPRO PRIMARY KEY,
    cod_categoria NUMBER CONSTRAINT FK_PROD_CODCAT REFERENCES CATEGORIA(COD_CATEGORIA),
    produto VARCHAR2(255) CONSTRAINT UK_PRODUTO_PROD UNIQUE
);

CREATE TABLE item_produto (
    cod_produto NUMBER,
    cod_materia_prima NUMBER,
    quantidade NUMBER CONSTRAINT NN_ITEMPROO_QUANT NOT NULL,
    CONSTRAINT PK_ITEMPRO_CODPRO_CODMAT PRIMARY KEY (COD_PRODUTO, COD_MATERIA_PRIMA), -- chave primária composta
    CONSTRAINT FK_ITEMPRO_CODPRO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO),
    CONSTRAINT FK_ITEMPRO_CODMATPRI FOREIGN KEY (COD_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA (COD_MATERIA_PRIMA)
);



SELECT * FROM user_constraints
WHERE TABLE_NAME = 'CATEGORIA';





----------------------------------
/*
DROP TABLE ITEM_PRODUTO;
DROP TABLE PRODUTO;
DROP TABLE MATERIA_PRIMA;
DROP TABLE CATEGORIA;
*/